RUN apt update \
    && apt install -y software-properties-common xdg-utils ca-certificates \
    && apt install -y fonts-firacode fonts-wqy-microhei ttf-wqy-zenhei fonts-arphic-ukai fonts-arphic-uming fonts-droid-fallback fonts-noto xfonts-base \
    && apt install -y yaru-theme-* \
    && apt install -y python3-pip ffmpeg graphviz neovim git ninja-build ccache \
    && apt install -y wget firefox evince \
    && apt install -y libgtk2.0-0 libxshmfence-dev libnss3-dev libatk-bridge2.0-dev libdrm-dev libgtk-3-dev libasound2-dev libcanberra-gtk-module libcanberra-gtk3-module \
    && rm -rf /var/lib/apt/lists/*
